platform:ios, '8.0'
target 'SavorX' do
pod 'MJRefresh', '~> 3.1.12'
pod 'RHNJKWebViewProgress', '~> 0.2.4'
pod 'IQKeyboardManager', '~> 4.0.6'
pod 'SDWebImage', '~> 3.8.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry', '~> 1.0.2'
pod 'GCDWebServer', '~> 3.3.3'
pod 'BGNetwork'
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/WeChat'
end
